# Generated by Django 5.2.4 on 2025-07-14 20:39

import django.contrib.postgres.indexes
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spamreport',
            name='reported_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='spamreport',
            name='target_phone',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['user'], name='core_authto_user_id_0bbce6_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_name'], name='idx_contact_name_prefix'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=django.contrib.postgres.indexes.GinIndex(fields=['contact_name'], name='idx_contact_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='core_user_phone_n_59ea9a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['name'], name='idx_user_name_prefix'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='idx_user_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
